### ISSUE TITLE
Jade integration

### ISSUE THREAD

**Issue by ghost** [ramidzkh/Applied-Botanics#11]
All info is present here: AppliedEnergistics/Applied-Energistics-2#6445

**Comment by ghost** [comment]
So this is due to AE2 not having compat for Jade implemented on Fabric: AppliedEnergistics/Applied-Energistics-2#6446

**Comment by ramidzkh** [comment]
I could disable the integration if jade is present I guess. It only adds `Device Online` or `Device Missing Channel` tooltips to the Fluix Mana Pool anyway

**Comment by ramidzkh** [comment]
Actually there's no point in me trying to do anything since AE2 will crash with Jade anyway. I'll leave the issue open until AE2 gets Jade support

**Comment by ghost** [comment]
> Actually there's no point in me trying to do anything since AE2 will crash with Jade anyway. I'll leave the issue open until AE2 gets Jade support

Sorry to burst your bubble but they have effectively said they are not planning on it. 😢 

Had to switch to WTHIT because I had no other choice.

**Comment by ramidzkh** [comment]
Closed by #17
