### ISSUE TITLE
Mana not "Filterable"

### ISSUE THREAD

**Issue by DarthB0ng** [ramidzkh/Applied-Botanics#12]
I mostly mean you can't use a level emitter to turn things on/off. Having full mana drives seems to cause issues with clogging up the return inventory of a pattern provider, specifically in the cobble to sand alchemy interaction in my case, being able to toggle my mana battery on/off of the network automatically would be cool.

**Comment by ramidzkh** [comment]
You should be able to right click a mana ring/tablet to set mana. Sorry for the late response
