### ISSUE TITLE
[Game Crash] 1.18.2 Fabric - Version 1.3.1

### ISSUE THREAD

**Issue by xR4YM0ND** [ramidzkh/Applied-Botanics#13]
The game crashes right after the window appears

[latest.log](https://gist.github.com/SpigotDE/232d885f2778d948d87afc9804bc3741)

No crash report

Without this mod, the game starts

**Comment by ramidzkh** [comment]
Disable MemoryLeakFix, or get WTHIT

**Comment by xR4YM0ND** [comment]
Do i have to get WTHIT , or can i use any mod based on waila ?

**Comment by ramidzkh** [comment]
I know that Jade doesn't work on AE2 yet, so keep it safe by using WTHIT
