### ISSUE TITLE
Items converted to Mana when entering the ME system

### ISSUE THREAD

**Issue by uselessSABOTAGE** [ramidzkh/Applied-Botanics#14]
I am using Modern Industrialization to macerate ores into dust.  When the macerator finishes its job, the item returns as Mana if the item is returned through a pattern provider.  This means, I cannot complete recipes, and further, it consumes my resources.  The workaround I found is to have the item go into a storage, in my case a dank in a dock, which then imports whatever goes into that storage into the ME system.

**Comment by ramidzkh** [comment]
Someone else has had a very similar issue with returned items being converted to mana recently... I wonder if it's a new mod. I cannot reproduce it myself though. What mods are you playing with?

**Comment by uselessSABOTAGE** [comment]
Hi, thanks for the reply.  I am working right now. In probably 10-12 hours from now I can provide a zip of all my mods.  I removed Applied Botanics, so I could complete my recipes and not lose my items, which means that mod won't be included in the zip. 

If you need anything else to troubleshoot this, please don't hesitate to ask.

**Comment by ramidzkh** [comment]
Could you also force a crash with F3+C and post the crash report here?

**Comment by uselessSABOTAGE** [comment]
This is the forced crash report.

[crash-2022-08-19_18.05.09-client.txt](https://github.com/ramidzkh/Applied-Botanics/files/9385742/crash-2022-08-19_18.05.09-client.txt)

**Comment by uselessSABOTAGE** [comment]
I have to break the mods into multiple uploads.  Here's part 1. 

[Mods Part 1.zip](https://github.com/ramidzkh/Applied-Botanics/files/9385747/Mods.Part.1.zip)

**Comment by uselessSABOTAGE** [comment]
Here is part 2.  Also, I because you asked for the crash report, I added back in Applied Botanics. I've also included the version I am using in the mod zip folder(s). 

Please let me know if you need anything else. 

[Mods Part 2.zip](https://github.com/ramidzkh/Applied-Botanics/files/9385750/Mods.Part.2.zip)

**Comment by ramidzkh** [comment]
> This is the forced crash report.
> 
> [crash-2022-08-19_18.05.09-client.txt](https://github.com/ramidzkh/Applied-Botanics/files/9385742/crash-2022-08-19_18.05.09-client.txt)

I can't even join a singleplayer world with these mods... I'll try the mods on your zips

**Comment by ramidzkh** [comment]
Your mods work, but I cannot reproduce this bug. Is it still happening? If so, send the world

**Comment by uselessSABOTAGE** [comment]
Ok, so, I had a busy morning and early afternoon today and was only able to spend the last hour or so troubleshooting this.  First, I looked at uploading the world as you requested, but it was way over the GitHub file size. Which caused me to decide to do a superflat creative world and keep everything small and then upload that world.  However, the single player world did *not* replicate this issue.  But, I added Applied Botanics back to my **server** and the issue persisted.  So, I did a quick screen capture and uploaded it to YouTube.  In the video, I toss some bronze dust (from Modern Industrialization) into a steam furnace (from Modern Industrialization) and then show my ME inventory.  You can see in the video as the bronze dust becomes ingots, instead of the system receiving a bronze ingot, I receive Mana.  

Here's the video: https://youtu.be/Nf3FAVbJLnA 

Please let me know what you want me to do.

**Comment by ramidzkh** [comment]
Yea I cannot reproduce this still, even using import busses instead of enable automatic extraction in the furnaces. The other person who's getting this bug said
```
the problem actually stopped after I reset some corrupted chunks nearby
a spectrum fusion shrine got wiped off the face of the earth and I used worldedit to regenerate it
but the corrupted chunks were completely disconnected from the bugged autocrafting setup
```
Perhaps you have corrupt chunks somewhere in your world..?

You'll need to figure out a way to send me that world. Dropbox or Google drive link or even an email to (ramidzkh at gmail dot com)

My setup:
![2022-08-21_10 34 52](https://user-images.githubusercontent.com/19631324/185770588-d8859bbb-cdeb-4300-a5ec-3e602fc60604.png)
![2022-08-21_10 34 47](https://user-images.githubusercontent.com/19631324/185770592-bfbceda1-9544-4d00-9dc4-7c05b72ac28b.png)

**Comment by uselessSABOTAGE** [comment]
So, I have created a backup of the server.  The world is just under 5 GB, and I am downloading it now.  This will take a while, and it is pretty late in my time zone, so I am heading to bed after I finish this message.  I considered your suggestion about corrupted chunks.  However, I don't have any experience with that.  I found some software called Amulet that should let me look into that.  I'll let you know what I find, but that'll be in the morning.

Also, in my instance the issue happens when any item is returned through an *export* bus into a pattern provider after being processed in some way by a machine/block from the mod Modern Industrialization.  This does *not* happen with vanilla blocks, such as a standard furnace.  It also does *not* happen with native AE2 blocks such as the inscriber or molecular assembler - even when returned directly to a pattern provider.  

I have a few closed loop crafting machines to handle processing/auto crafting for Modern Industrialization.  I put several pattern providers (full block) into a dank dock.  The dank receives the items from the pattern provider when I initiate a craft via the ME system.  The closed loop ME system on the other side of the dank will import anything from the dank.  Then storage busses tell items where to go.  They're filtered on insertion only.  I then have *export* busses set to feed the pattern provider attached to the dank, which originally fed the pattern, to return the item(s) which were crafted/processed by the closed loop system.  I have had no issues with this until after adding Applied Botanics.  It happened immediately after installing it.  

But, as mentioned before, it doesn't happen in a single player world. Which causes me to wonder about your suggestion of corrupted chunks.  I will let you know what I find out via Amulet tomorrow.

Thanks for continuing to attempt to solve this.  I really appreciate your time.

**Comment by ramidzkh** [comment]
You don't need to send me your whole world! Just select the regions where your relevant chunks are (you can exclude 99% of the regions folder, the bulk of any world), and send the rest

**Comment by uselessSABOTAGE** [comment]
So, I couldn't figure out how to use Amulet.  I don't know how to tell if any of my chunks are corrupt.  I don't have any visual chunk errors. 

I had to learn how to do what you wanted.  To keep the world size down, I created a superflat world with the same seed, then copy/pasted the region file into that world.  After I loaded the world, I teleported into the region and none of my stuff seems to work.  Specifically, import/export doesn't appear to work.  I tried test smelting some items and they stayed in the furnace.  Steam doesn't appear to export from ME into Modern Industrialization machines/blocks. 

You requested the world, here it is.  The region I imported is at -1169, 134, 2813.  Perhaps you know something I don't when you cut/paste a region like this.  I hope you can make this work.  Otherwise, I am not sure what else we can do. 


[Server Region.zip](https://github.com/ramidzkh/Applied-Botanics/files/9389140/Server.Region.zip)

**Comment by uselessSABOTAGE** [comment]
Hello,

It has been a while since I shared the server region's file, and I was wondering if you had a chance to review it.

**Comment by ramidzkh** [comment]
Yea, can't reproduce either. I'll leave this issue open in case anyone else manages to reproduce it with another method

**Comment by uselessSABOTAGE** [comment]
Thanks for the update. 

I will let you know if I discover anything else too.

**Comment by ramidzkh** [comment]
I finally managed to reproduce it thanks to a world from another player, and I think I have a fix. Will try to release in a few hours

**Comment by uselessSABOTAGE** [comment]
I can't wait to try the fix. Thanks for continuing to work this issue.
