### ISSUE TITLE
Add virtual mana storage within ME

### ISSUE THREAD

**Issue by Gitcrafter** [ramidzkh/Applied-Botanics#2]
Hello, do you have any plans on adding mana storage cells?

**Comment by ramidzkh** [comment]
I don't want to add mana storage cells exactly (I'd rather people try to stick with botania), but feel free to give ideas. For now you can easily store a lot of mana by putting tens of mana pools linked to a Mana P2P with a dominant spark for anything which needs mana, and have another recessive Mana P2P if you generate mana elsewhere.

**Comment by Gitcrafter** [comment]
I just asked, because AE2 addons that add support for specific mods usually add storage cells for that mods special resources, like Applied Mekanistics for Mekanism Chemicals and there were ones on 1.12 that added cells for Botanias Mana or Thaumcrafts Essentia respectively

**Comment by sonicer105** [comment]
I feel like adding storage to the mod would really go against Vazkii's wishes as it would be a step towards numerical mana which he has expressly said no to.

**Comment by Gitcrafter** [comment]
then I take that as a no

**Comment by ramidzkh** [comment]
I think it's worth keeping this issue open if someone suggests a better idea

**Comment by ramidzkh** [comment]
Still not resolved on Forge, but will wait for feedback first

**Comment by Demsli** [comment]
Storage bus for Mana pools? It keeps the idea of not breaking the main mod. But also shows you the amount of mana in the system. Yeah it will show numbers, but Integrated Dynamics has already taken this blame)

**Comment by 62832** [comment]
> Still not resolved on Forge, but will wait for feedback first

Do it on Forge as well, for no particular reason other than that it would be funny.

EDIT: Having said that, it may be worth considering the overall balance between AE2 and Botania as a result. As a balancing measure, I would suggest changing the storage cells to use terrasteel as opposed to manasteel to craft, in order to not make them quite as accessible this early on.
