### ISSUE TITLE
[Forge] Spark can't be placed on the Mana P2P Tunnel

### ISSUE THREAD

**Issue by StarskyXIII** [ramidzkh/Applied-Botanics#21]
Environment
Forge: 40.1.84
Applied Energistics 2: 11.6.1-beta
Applied Botanics Addon: 1.0.2-alpha
Botania: 1.18.2-435

**Comment by ramidzkh** [comment]
I need more information. Please re-open if issue still persists

**Comment by StarskyXIII** [comment]
That build works fine for me, thank you
