### ISSUE TITLE
infinite mana

### ISSUE THREAD

**Issue by bingyingzizz** [ramidzkh/Applied-Botanics#23]
Put mana spreader in front of import bus, and mana will keeps increasing.
I don't know if it is a bug.
![2022-11-26_11 40 31](https://user-images.githubusercontent.com/119091460/204071150-aff9cfc1-0a07-41d7-be6a-cda50dded208.png)

**Comment by bingyingzizz** [comment]
![2022-11-26_11 50 30](https://user-images.githubusercontent.com/119091460/204071383-c4e65c1f-dcec-4158-a55f-93c11d76960a.png)
Fluix mana pool CAN'T actually save mana and use it, but it is able to use spark to transfer mana

**Comment by bingyingzizz** [comment]
forge 40.1.76
appmek 1.2.2
appbot [FORGE]1.02-alpha
AE11.6.6

**Comment by ramidzkh** [comment]
I can't reproduce (anymore?). Please open another issue if you somehow get this again
