### ISSUE TITLE
Corporea Crystal Cube not displaying number of items for items in ME system

### ISSUE THREAD

**Issue by orionSquared** [ramidzkh/Applied-Botanics#33]
As mentioned in the title, when I connect my ME system to my corporea network, everything works great. Except the crystal cube doesn't show a correct number. It says there's zero in the system. I can still punch the cube to extract items and they give me the items I want, but the number goes negative and then resets back to zero. If I place down an AE2 item next to it (I've put storage monitors next to each cube so that it'll display my number of items), it'll have the correct number that's in the AE system for a few seconds but then resets to zero again.

Thanks

**Comment by ramidzkh** [comment]
Do you have security on the network? If so, it's probably not allowing any blocks from your Corporea network to access it

**Comment by orionSquared** [comment]
I do have security on it, but I put in a blank card that allowed everything. Also, I'm able to request from the corporea index and I'm able to pull from the crystal cubes with no issues, so I know they're working.

**Comment by ramidzkh** [comment]
Security was removed so this should be fixed?
