### ISSUE TITLE
Comparator on fluix mana pool causes massive amount of neighbor updates leading to severe lag and crashes with a large enough network

### ISSUE THREAD

**Issue by jpenilla** [ramidzkh/Applied-Botanics#38]
A setup like the following is enough to almost kill the server:
![2023-04-01_09 50 30](https://user-images.githubusercontent.com/11360596/229304008-080961de-8139-421f-97a2-7199a1cfeb48.png)

https://spark.lucko.me/KTTAejI7BT

I noticed this when I crashed my server by replacing a mana pool in an existing setup with a fluix mana pool connected to a pretty large me network. I got log messages from the collecting neighbor updater about >1000000 chained updates, then a crash.

I'm using the comparator to stop generating mana when the pool/network is full enough, so a level emitter might be a better solution, but this should probably be addressed in some fashion anyways.

**Comment by ramidzkh** [comment]
I can't really reproduce this big of a lag spike, but could you see if [this build](https://github.com/ramidzkh/Applied-Botanics/suites/12274951303/artifacts/650047998) helps?

**Comment by ramidzkh** [comment]
Nevermind, I can feel the lag and the console does fill up with `[Server thread/ERROR] (Minecraft) Too many chained neighbor updates. Skipping the rest. First skipped position:`. The above build does seem to fix it. Will profile soon, or could you provide a profile?

**Comment by jpenilla** [comment]
It seems like the lag is fixed, but now the comparator output doesn't change until I place something next to the comparator to force a neighbor update.

**Comment by ramidzkh** [comment]
It should be updating every 10 ticks at most, and seems to work for me. Could you please find the minimal mod list which reproduces this issue and screenshot the setup?

![image](https://user-images.githubusercontent.com/19631324/232658054-d97b2da0-d27f-419c-bfbc-ac1f0d393d32.png)
My setup has an ME IO port with a creative cell giving Mana, a 256k inside the drive and it seems to change comparator level on its own

**Comment by jpenilla** [comment]
Can confirm it works with just appbot and it's dependencies.

The modlist where it doesn't update is kind of large (https://github.com/TeamAOF/All-of-Fabric-6/blob/main/MODLIST.md) so not really looking forward to figuring out which is conflicting... but will try and get around to it sometime.

I'm using level emitters now, so it would be fine with me if you closed this issue with the fix, and then I or someone else can open a new issue at the appropriate repo when it's found what the conflict is.

**Comment by jpenilla** [comment]
Looks like the issue is I updated to 1.5.3 of the modpack: https://github.com/TeamAOF/All-of-Fabric-6/issues/202

Means it has to be one of these mods: https://github.com/TeamAOF/All-of-Fabric-6/blob/main/changelogs/changelog_mods_1.5.3.md

edit: 
The cause of the missing updates was determined to be MineCells.

**Comment by mim1q** [comment]
I've updated Mine Cells with the fix applied. [Modrinth](https://modrinth.com/mod/minecells/version/1.4.3), CurseForge is under review.
