### ISSUE TITLE
[FORGE // 1.18.2] Can't put Spark on mana p2p

### ISSUE THREAD

**Issue by Gogo08190** [ramidzkh/Applied-Botanics#39]
Hello, 
I have a problem with the applied botanics addon.
I can't put a spark on the mana p2p, can you help me please ?

Mc version : 1.18.2
Forge version : 40.2.0
Applied botanics version : 1.0.2-alpha

**Comment by ramidzkh** [comment]
Fixed in [1.0.3 for Forge on Minecraft 1.18.2](https://github.com/ramidzkh/Applied-Botanics/actions/runs/4697430546) (also on CurseForge and Modrinth)
