### ISSUE TITLE
Forge || 1.18.2 --> Mana generation glitch ex-nihilo

### ISSUE THREAD

**Issue by SNEAXIII** [ramidzkh/Applied-Botanics#40]
Hello, after using your mod in many cases, I noticed a quite annoying bug. Indeed, it allows you to generate an infinite amount of mana from nothing. For example, with the setup shown in the image and 4 acceleration cards, I can fill a fabulous mana pool in about 7 seconds, a basic one in 5.5 seconds, and a diluted one in 1 second. This bug occurs with each spreader and each mana pool. To simplify, the spreader acts as an infinite mana source when using a "me importer".

Thanks for this great mod :)

![image](https://user-images.githubusercontent.com/74428850/232239738-1c191c8e-8cdf-484f-a154-f3be43313978.png)

MineCraft version : 1.18.2
Forge version : 40.2.0
Applied botanics version : 1.0.3
Applied Energistics 2 version : 11.7.0

**Comment by ramidzkh** [comment]
Could not reproduce on 1.19.2, so must be 1.18.2 specific. I'll look into it soon

**Comment by SNEAXIII** [comment]
Thanks ;)

**Comment by ramidzkh** [comment]
Could not reproduce
