### ISSUE TITLE
Comparator on Fluix Pool crashes server

### ISSUE THREAD

**Issue by IanLuminus** [ramidzkh/Applied-Botanics#43]
Had this happen on AllTheMods 8 pack, AppliedBotanics 1.4.2 Forge, AE2 12.9.2, couple other AE addons that.. I don't think are causing this? Anyways. First Gist is when the Comparator is already in place (part of generation flowers automation) and I try to set down the Fluix Pool, second is if the existing Comparator is broken, the Fluix Pool is set down, then a Comparator attached to it in a different location from the first crash.

If it matters any, there is a Fluix Cable under where I'm setting the Pool.

https://gist.github.com/IanLuminus/2e23f5f8dcb6b212de7a3a21d94971b8

https://gist.github.com/IanLuminus/f312bce5bc6d36e18f16da872f603b40

**Comment by ramidzkh** [comment]
Try [this build](https://github.com/ramidzkh/Applied-Botanics/suites/12591466083/artifacts/673469527)

**Comment by IanLuminus** [comment]
Turns into this with a black and purple checkered screen at the beginning of the game loading, crashing before main menu.

https://gist.github.com/IanLuminus/5e8e36326138e806680c8cadaa154cde

For what it's worth, I can simulate the Comparator by using a Level Emitter.

Also, you might want to point out somewhere that Emitter, Interface, Export Bus, etc functionality for moving Mana needs a Band of Mana (maybe a tablet?) for specifying the "fluid" being moved. I only found out after checking the few not-unlisted videos on your Youtube.

EDIT: Is it possible this is happening because the Fluix Pool seemingly has no "tank" for the Mana itself? If I don't have a Mana drive in the ME system attached to it, the Spreaders don't want to fire bursts into the pool. I would just do Import Busses on the Spreaders themselves, but I'm using a Mana Detector and Sequencer from RFTools to automate feeding the flowers so no resources are wasted.
![2023-05-01_12 49 45](https://user-images.githubusercontent.com/106407705/235500479-e0cad252-e369-4a84-9848-3b57b5891b6c.png)
The Sequencer is under the Detector, same setup that Dire did in his ATM8 playthrough a while ago, I just updated it to Applied Botanics so I have lots more storage than a 5*5 of normal Mana Pools.

**Comment by TheEye2108** [comment]
Hi im getting the same same error on version 1.4.2 Valhelsia 5 but for me the game worked for a while and then crashed. Not sure for how long but know when i attach a comparator to a flux mana pool the game crashes instantly had to use world edit to remove comp to enter the world again.

**Comment by ramidzkh** [comment]
@TheEye2108 Could you try this build and please confirm if it fixes the bug? [Applied-Botanics-0.0.0.zip](https://github.com/ramidzkh/Applied-Botanics/files/12535214/Applied-Botanics-0.0.0.zip)

**Comment by TheEye2108** [comment]
The comparator dosn't break the game any more but all other applied botanics items are broken :D
![2023-09-06_17 36 56](https://github.com/ramidzkh/Applied-Botanics/assets/20605421/afa6f6b4-06bd-4637-9c35-848984f69e54)

**Comment by ramidzkh** [comment]
Ah I forgot to run datagen... whoops!

Well anyway, the full release will fix this, wait for 1.4.4 Fabric and Forge in a few minutes

**Comment by ramidzkh** [comment]
Please open a new issue if 1.4.4 doesn't fix this
