### ISSUE TITLE
Server freeze when a Fluix Mana Pool is connected and a full world save is requested

### ISSUE THREAD

**Issue by AraragiEro** [ramidzkh/Applied-Botanics#45]
server version is 1.19.2 forge 43.2.13.

**Comment by ramidzkh** [comment]
Fixed, but unfortunately it isn't in the version I just release, and I don't want to publish a new version right now. If anyone is interested, I can post a jar

**Comment by ramidzkh** [comment]
Fixed by https://github.com/ramidzkh/Applied-Botanics/commit/0cbd04449fcddae4057ac01ae450c7859fd93d9b
