### ISSUE TITLE
Mana storage cell sizes differ from AE2

### ISSUE THREAD

**Issue by grekdawid26** [ramidzkh/Applied-Botanics#46]
Hello,
Very simple issue here:

Is there a reason that this mod uses a 1000 multiplier of kB instead of 1024 (like the rest of AE2)?

When you hover over the cells this just looks weird - you know... all the cells say I'm 1024/4096/16384/65536/..., and these ones say 1000/4000/16000/64000/... ;/

I'm not great at Java, so that might be a wrong place to change it, but I looked for it anyway - looks very easy to change - just two digits (maybe... i'm not sure, if it's the only place or even the place):
[`this.totalBytes = kilobytes * 1000;`](https://github.com/ramidzkh/Applied-Botanics/blob/46f1b0f0506e820810973d508639e81967788b29/src/main/java/appbot/item/ManaCellItem.java#L38C39-L38C43)

If it's not a problem I would appreciate greatly if you could think of that small little beautiful change.
Sorry, but stuff like that bother me a little bit.

**Comment by ramidzkh** [comment]
We changed it to 1000 to better suit Botania; in vanilla all the item caps are some power of 2 (1, 8, 16, 32, 64, etc), but in Botania most things use like 1000 mana or 500k mana, etc. Also, mana tablets also hold something like 500k mana or 2M mana, nothing really a power of 2
