### ISSUE TITLE
Forge mod lacking features?

### ISSUE THREAD

**Issue by Jatoxo** [ramidzkh/Applied-Botanics#48]
Sorry to spam the issues, I couldn't find any documentation or information anywhere

I'm playing the ATM7 - To The Sky Modpack which includes Applied-Botanics-1.0.1.

But, the only item I can find in JEI are Mana P2P tunnels, no mana drives or fluix mana pools. Is this a server config issue or is the forge mod just that outdated?

**Comment by ramidzkh** [comment]
Applied Botanics for older Minecraft versions used to prioritize Fabric over Forge. If there is an Applied Botanics version past [1.0.2-alpha for Forge on Minecraft 1.18.2](https://github.com/ramidzkh/Applied-Botanics/releases/tag/forge%2F1.0.2-alpha), it should have full feature parity.

**Comment by Jatoxo** [comment]
Thanks! [This version](https://github.com/ramidzkh/Applied-Botanics/releases/tag/forge%2F1.0.3) does have the fluix pool and mana drives
