### ISSUE TITLE
[Fabric 1.19.2/0.14.22] Latest version of Applied Botanics crashes with MEGA CELLS on start-up

### ISSUE THREAD

**Issue by pokesmells** [ramidzkh/Applied-Botanics#53]
[crash-2023-10-01_23.11.35-client.txt](https://github.com/ramidzkh/Applied-Botanics/files/12779632/crash-2023-10-01_23.11.35-client.txt)

Downgrading Applied Botanics works to stop the crash

**Comment by ramidzkh** [comment]
MEGA needs an update @62832

**Comment by 62832** [comment]
Looks like I have to switch back to the 1.19 branch in the end...
