### ISSUE TITLE
Creative ME Mana Cell can hold items

### ISSUE THREAD

**Issue by IPLTeam7** [ramidzkh/Applied-Botanics#59]
As said in the title the Creative ME Mana Cell can hold items by just using the Cell Worbench from Applied Energistics , this can break some progression in modpacks.

How to reproduce : 

1. Put the Creative ME Mana Cell in the Cell workbench
2. Drag and drop a item from JEI
3. Put you cell in a ME Drive

Versions of mods / forge : 
- Forge 1.18.2-40.2.9
- Applied Energistics 2 : appliedenergistics2-forge-11.7.6
- Applied Botanics Addon : Applied-Botanics-1.0.3
- JEI : jei-1.18.2-9.7.1.255
![bug ABMANA](https://github.com/ramidzkh/Applied-Botanics/assets/94351621/0c19d854-c173-4d55-b357-4ecae31dbb39)
![bug ABMANA2](https://github.com/ramidzkh/Applied-Botanics/assets/94351621/4cd031e7-a35e-4886-ad0b-89b2c24a3ce3)

**Comment by ramidzkh** [comment]
~~Could you update to [1.4.4 for Forge on Minecraft 1.19.2](https://github.com/ramidzkh/Applied-Botanics/releases/tag/forge%2F1.4.4)~~

**Comment by ramidzkh** [comment]
Nevermind, this is 1.18.2. I'm not going to update 1.18.2, but you can work around this issue in your pack by removing the Creative ME Mana Cell recipe and instead giving a creative Mana pool from Botania, and using a storage bus
