### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by Leosh11** [ramidzkh/Applied-Botanics#6]
heyo i'am trying to connect these Mana Pools with other Mana pools with the P2P network and it just doesn't work. I'am getting desperate.
![2022-06-01_22 44 56](https://user-images.githubusercontent.com/62500760/171503475-a080e34f-df28-4b0d-987e-e6d5dfb50d2e.png)

**Comment by ramidzkh** [comment]
Resolved on CF. iirc improper setup
