### ISSUE TITLE
Magic pool unable to store magic when exceeding integer limit

### ISSUE THREAD

**Issue by gjmhmm8** [ramidzkh/Applied-Botanics#63]
When the magic value exceeds the integer limit, the magic cannot be stored in the magic pool. This issue can be problematic for players who have accumulated a large amount of magic.
I suggest adjusting the magic pool’s maximum value to LONG to accommodate higher amounts of magic. Alternatively, you can set the maximum magic value in the magic pool to half of the integer limit, and any excess magic will not be displayed in the pool. This will prevent the issue of magic being unable to be stored when exceeding the integer limit.
Thank you for your attention to this issue. I look forward to seeing a resolution in a future update.

**Comment by ramidzkh** [comment]
Problem is, Botania cannot support this while also being a Mana pool (for use in typical Mana pool places like Mana recipes). Can you replace the Mana pool with an ME Interface instead? ME Interfaces can accept Mana bursts, and should be fine

**Comment by gjmhmm8** [comment]
When the mana in the Mana Pool exceeds half of the INT limit, set the displayed mana in the Mana Pool to half of the INT limit to solve the problem.

**Comment by gjmhmm8** [comment]
The ME interface currently cannot accept mana now in 1.20.1
