### ISSUE TITLE
Mod not working part 2

### ISSUE THREAD

**Issue by kaliflowerx3** [ramidzkh/Applied-Botanics#7]
fabric api version: 0.54.0
fabric version: 0.14.6
ae2 version: 11.0.0
applied botanics addon version: tried 1.2.0 and 1.2.1

Everything past version 1.0.0 doesn't work. Can't create p2p tunnels (tried rc with a spark) and even when grabbed from creative they don't transfer mana. Same setup works in version 1.0.0

**Comment by ramidzkh** [comment]
Can you send a screenshot of the 1.0.0 working setup?
Also petals are used for attunement now, but I'll also add sparks.

**Comment by kaliflowerx3** [comment]
Ok we were able to get it working, my mistake. the petals is a good tip, maybe that should be added to the curseforge page? Sorry for the confusion.
