### ISSUE TITLE
MANA P2P don'st work on AllTheMods 7

### ISSUE THREAD

**Issue by SireTeddy** [ramidzkh/Applied-Botanics#8]
Hello, 
I write this message because the mod doesn't work on ATM 7 modpack.
I dan have mana P2P tunnels, place it, i can configure it correctly, but when mana is on the input mana pool, it don't be output on the other mana pools, or other block wich use mana (terrastrial, or runic altar). can you fix it ? 
mods version is : 1.0.1
Forge 40.1.31
minecraft 1.18.2

**Comment by ramidzkh** [comment]
You need to use mana spreaders to push mana into the P2P input side

**Comment by SireTeddy** [comment]
It slow to push mana into p2p tunnel or not with spreaders ?

**Comment by ramidzkh** [comment]
You can use a mana spark into a P2P also, but the P2P tunnel needs to be facing up
